name: First Workflow

on:
  push:
  pull_request:
  
jobs:
    myfirstjob:
              name: First Job
              runs-on: ubuntu-latest
              
              defaults:
                run:
                  working-directory: ./frontend
        
              strategy:
                matrix:
                  node-version: [18.x]
        
              steps:
              - name: Checkout code
                uses: actions/checkout@v3 #Clone the repo on the runner Ubuntu
                
              - name: Setup Node ${{ matrix.node-version }}
                uses: actions/setup-node@v2.5.2
                with: 
                  node-version: ${{ matrix.node-version}}
              
              - name: Install dependencies
                run: npm install
                
              - name: Run tests
                run: npm test
                
              - name: Build Docker image
                if: ${{ success() }}
                uses: docker/build-push-action@v2
                with:
                  context: .
                  push: true
                  tags: gena/capstone-app:latest
                  
    mysecondjob:
              needs: [myfirstjob] #Wait for the first job to be finished to start with the second
              name: Second Job
              runs-on: macos-latest
              steps:
              - name: Step One
                run: date
    mythirdjob:
              name: Third Job
              runs-on: windows-latest
              steps:
              - name: Step One
                run: date
