name: First Workflow

on:
  push:
  pull_request:
  
jobs:
    first:
              name: Preparing environment
              runs-on: ubuntu-latest
              
              defaults:
                run:
                  working-directory: ./capstone-app
        
              strategy:
                matrix:
                  node-version: [18.x]
        
              steps:
              - name: Checkout code
                uses: actions/checkout@v3 #Clone the repo on the runner Ubuntu
                
              - name: Setup Node ${{ matrix.node-version }}
                uses: actions/setup-node@v2.5.2
                with: 
                  node-version: ${{ matrix.node-version}}
              
              - name: Install dependencies
                run: npm install
                
              - name: Run tests
                run: npm test
                
                
             
                  
             
                  
                  
    second:
              needs: [first] #Wait for the first job to be finished to start with the second
              name: Set Docker if test are passed
              runs-on: ubuntu-latest
              defaults:
                run:
                  working-directory: ./capstone-app
              
              steps:
               - name: Checkout
                 uses: actions/checkout@v2
                
               - name: Login to Docker Hub
                 uses: docker/login-action@v2
                 with: 
                  registry: ghcr.io
#                   username: ${{ secrets.DOCKERHUB_USERNAME }}
#                   password: ${{ secrets.DOCKERHUB_TOKEN }}
                  username: ${{github.actor}}
                  password: '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'
                  
               -
                name: Set up docker Buildx
                uses: docker/setup-buildx-action@v2

                
               - 
                name: Build Docker image
#                 if: ${{ success() }}
                uses: docker/build-push-action@v4
                with:
                  context: ./capstone-app
#                   file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
    mythirdjob:
              name: Third Job
              runs-on: windows-latest
              steps:
              - name: Step One
                run: date
